### ISSUE TITLE
pytorch0.3 RuntimeError: value cannot be converted to type float without overflow: inf???

### ISSUE THREAD

**Issue by hdjsjyl** [Goingqs/PyramidBox#14]
/home/lshi22/.local/lib/python3.5/site-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Initializing weights...
Loading Dataset...
Training SSD on WiderFace
/home/lshi22/.local/lib/python3.5/site-packages/torch/autograd/functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements. Falling back to deprecated pointwise behavior.
return tensor.masked_fill(mask, value)
front and back Timer: 22.854674100875854 sec.
iter 0 || Loss: 71.4618 ||
Loss conf: 38.856040954589844 Loss loc: 13.214371681213379
Loss head conf: 28.07379722595215 Loss head loc: 10.708907127380371
lr: 0.001
Saving state, iter: 0
Traceback (most recent call last):
File "train.py", line 241, in 
train()
File "train.py", line 188, in train
loss_l, loss_c = criterion(tuple(out[0:3]), targets)
File "/home/lshi22/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in call
result = self.forward(*input, **kwargs)
File "/home/lshi22/PyramidBox/layers/modules/multibox_loss.py", line 102, in forward
loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))
File "/home/lshi22/PyramidBox/layers/box_utils.py", line 246, in log_sum_exp
return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True)) + x_max
RuntimeError: value cannot be converted to type float without overflow: inf

@Goingqs  I think it is an error for pytorch0.3, how you train your model in pytorch0.3 version?

**Comment by Goingqs** [comment]
Maybe your batch size is too small. A smaller lr may help

**Comment by hdjsjyl** [comment]
@Goingqs   My batch size is 16. I think it is not problem of batch size.

**Comment by hdjsjyl** [comment]
@Goingqs   My batch size is 16. I think it is not problem of batch size.

**Comment by Edwardmark** [comment]
@hdjsjyl @Goingqs  I met the same problem, in 1080TI * 2 ,I can only set batch size to 8, and accum_batch_size to 32, if greater than that, will cause cuda outof memory error.

**Comment by Edwardmark** [comment]
@Goingqs @hdjsjyl  And I often met with the following error randomly:  
iter 470 || Loss: 128.9373 ||
Loss conf: 70.57467651367188 Loss loc: 25.275745391845703
Loss head conf: 47.26240158081055 Loss head loc: 18.91145133972168
lr: 0.001
Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train()
  File "train.py", line 175, in train
    images, targets = next(batch_iterator)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/app/data/widerface.py", line 101, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "/app/data/widerface.py", line 124, in pull_item
    img, boxes, labels = self.transform(img, target[:, :4], target[:, 4])
IndexError: too many indices for array

Any ideas? Thans, guys.

**Comment by hdjsjyl** [comment]
@Edwardmark  Actually we always meet the same problem. So I think it is a common problem. We should check the code carefully.

**Comment by Edwardmark** [comment]
@hdjsjyl That is because the author fine-tune the model, but we train from scratch.

**Comment by nuanyang123** [comment]
@hdjsjyl  Yeah,I also got the same problem randomly. I think the problem exists in the RandomBaiduCrop.

**Comment by nuanyang123** [comment]
@hdjsjyl  So did you solve that problem? If so, would you please share me the way to solve this troublesome problem?

**Comment by YueXiNPU** [comment]
![default](https://user-images.githubusercontent.com/34571270/49210451-37a54700-f411-11e8-90e4-3e38778e8ab3.png)

**Comment by YueXiNPU** [comment]
I also meet the same question. Is there any person who solved the problem?

**Comment by Yuxiang1995** [comment]
@Edwardmark @YueXiNPU 
Hey,I think I solve this problem.An annotation of picture causes this error.

0--Parade/0_Parade_Parade_0_452.jpg
2--Demonstration/2_Demonstration_Political_Rally_2_444.jpg
39--Ice_Skating/39_Ice_Skating_iceskiing_39_380.jpg
46--Jockey/46_Jockey_Jockey_46_576.jpg

You can find the annotation of these picture is (1,0,0,0,0). Because the weight and height is 0,the tensor target is a empty tensor,and it cause "to many indices for array"

So, you need to remove the annotation of these picture from your annotation file

**Comment by limacv** [comment]
Some images in the WIDER_FACE have no face. The corresponding annotations are [xxx.jpg 1 0 0 0 0]. Just remove these images. (I found 4 of them in training dataset)

**Comment by upsx** [comment]
> /home/lshi22/.local/lib/python3.5/site-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
> RequestsDependencyWarning)
> Initializing weights...
> Loading Dataset...
> Training SSD on WiderFace
> /home/lshi22/.local/lib/python3.5/site-packages/torch/autograd/functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements. Falling back to deprecated pointwise behavior.
> return tensor.masked_fill(mask, value)
> front and back Timer: 22.854674100875854 sec.
> iter 0 || Loss: 71.4618 ||
> Loss conf: 38.856040954589844 Loss loc: 13.214371681213379
> Loss head conf: 28.07379722595215 Loss head loc: 10.708907127380371
> lr: 0.001
> Saving state, iter: 0
> Traceback (most recent call last):
> File "train.py", line 241, in
> train()
> File "train.py", line 188, in train
> loss_l, loss_c = criterion(tuple(out[0:3]), targets)
> File "/home/lshi22/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in call
> result = self.forward(*input, **kwargs)
> File "/home/lshi22/PyramidBox/layers/modules/multibox_loss.py", line 102, in forward
> loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))
> File "/home/lshi22/PyramidBox/layers/box_utils.py", line 246, in log_sum_exp
> return torch.log(torch.sum(torch.exp(x-x_max), 1, keepdim=True)) + x_max
> RuntimeError: value cannot be converted to type float without overflow: inf
> 
> @Goingqs I think it is an error for pytorch0.3, how you train your model in pytorch0.3 version?

I have met the same problem, and tried the other' suggestion: reduce the lr. Luckily, it works.
