### ISSUE TITLE
GPU memory issue.

### ISSUE THREAD

**Issue by Edwardmark** [Goingqs/PyramidBox#18]
@hdjsjyl @Goingqs Using batchsize 32, I got the following error when run train.py, I use two 1080TI and 32G memory, can you help me out please?
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

I understand that it is a gpu memory issue, but I use the same setting as yours, why can't I train with batch 32? I change batch size to 16, and now it works for the first iteration, but failed next, got the following error:  
root@bfffba56f59a:/app# python3 train.py 
Initializing weights...
Loading Dataset...
Training SSD on WiderFace
/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_fill_(mask, value)
front and back Timer: 6.264386892318726 sec.
iter 0 || Loss: 59.1287 ||
Loss conf: 30.951845169067383 Loss loc: 13.884753227233887
Loss head conf: 20.91655158996582 Loss head loc: 7.667636871337891
lr: 0.001
Saving state, iter: 0
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 240, in <module>
    train()
  File "train.py", line 185, in train
    out = net(images)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 73, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 83, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/app/pyramid.py", line 211, in forward
    c3 = self.layer2(c2)    #S8
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/app/pyramid.py", line 84, in forward
    out = F.relu(self.bn2(self.conv2(out)),inplace=True)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by Edwardmark** [comment]
@Goingqs Hi, I can only run the train.py code setting batch_size = 8, and accum_batch_siz = 32 using 2x1080TI, occupying nearly 10G gpu memory each. Why you can use batch_size = 32 and not encounter cuda out of memory?Please help me out or give some clues, thank you very much. Your enthusiasm  and professionism impressed me deeply.

**Comment by hdjsjyl** [comment]
@Edwardmark  how much is your learning rate?

**Comment by hdjsjyl** [comment]
@Edwardmark  The code does not use "accum_batch_size" and "iter_size", so the problem does not have business with these two parameters.

**Comment by Edwardmark** [comment]
@hdjsjyl Hi, so with 2 * 1080TI, I use batchsize = 8, and the GPU memory is full, why is that? Why the author can use batch_size = 16? My learning rate is 0.001, 
Another question, I only found one image with height = 0,and deleted it. And I checked the data, but still met the following error, maybe caused by list format? Can you give out a list that can be trained without error? Thanks.
File "train.py", line 240, in 
train()
File "train.py", line 175, in train
images, targets = next(batch_iterator)
File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 267, in next
return self._process_next_batch(batch)
File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 55, in 
samples = collate_fn([dataset[i] for i in batch_indices])
File "/app/data/widerface.py", line 99, in getitem
im, gt, h, w = self.pull_item(index)
File "/app/data/widerface.py", line 119, in pull_item
img, boxes, labels = self.transform(img, target[:, :4], target[:, 4])
IndexError: too many indices for array
Would you please give me some clue?

**Comment by hdjsjyl** [comment]
@Edwardmark   First, there are more than one image with height or width is equal to zero;
Second, I can not run it with learning rate of 0.001, which has gradient is inf. So I do not know the real reason. I always am scared of that the author of the code forgets to tell us something, but I am not sure of what is that information.

**Comment by Edwardmark** [comment]
@hdjsjyl Thanks for your reply, let's find out the reason and discuss it. I modified the list and found out that there is 4 imgs that is zero.
