### ISSUE TITLE
Can we upgrade to pytorch 0.4?

### ISSUE THREAD

**Issue by kodonnell** [Goingqs/PyramidBox#2]
As above

**Comment by kodonnell** [comment]
Yes, there were some warnings etc. when trying to run it. Also, I was trying to force CPU, and it worked on 0.3.1 but segfaulted on 0.4.

**Comment by hdjsjyl** [comment]
@ZeR0ll @kodonnell   Are you successful to run the program? I always meet some problems.

**Comment by kodonnell** [comment]
Yes. Maybe post a new issue if you're having problems.

**Comment by hdjsjyl** [comment]
@kodonnell can you share your wider list? I have a little problems about it. And you use pytorch3.0 or 4.0, cpu or gpu version? Thanks.

**Comment by Edwardmark** [comment]
@kodonnell  would you tell me your speed run pyramid box? I found it too slow.

**Comment by kodonnell** [comment]
Please keep all comments related to this issue (upgrading to pytorch 0.4). If you want to ask a different question, please start a new issue. FYI I'm not the maintainer ...

**Comment by Edwardmark** [comment]
@kodonnell I try to upgrade to pytorch4.0, it works.

**Comment by YiLiangNie** [comment]
> @kodonnell I try to upgrade to pytorch4.0, it works.
I want to upgrad to pytorch 0.4, so what do I need to modify? thank you!

**Comment by Edwardmark** [comment]
@YiLiangNie Just modified the bug it occurs, the solution of any bug can be found in google.

**Comment by ForestWang** [comment]
when I run the detect_face function with pytorch 0.4, get below error:

Loading model..
Finished loading model!
Process FOLD-%02d 0
shrink:1
test.py:46: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x = Variable(x.cuda(), volatile=True)
/home/zhijin.wang/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1749: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/zhijin.wang/work/PyramidBox/pyramid.py:254: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(torch.cat([p for p in prior_boxs],0),volatile=True)
/home/zhijin.wang/work/PyramidBox/pyramid.py:255: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors_head = Variable(torch.cat([p for p in prior_head_boxes],0),volatile=True)
Traceback (most recent call last):
  File "test.py", line 275, in <module>
    fddb_evaluate()
  File "test.py", line 263, in fddb_evaluate
    bboxes = detect_face(img, 1)
  File "test.py", line 49, in detect_face
    y = net(x)
  File "/home/zhijin.wang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhijin.wang/work/PyramidBox/pyramid.py", line 302, in forward
    self.priors.type(type(x.data))                  # default boxes
  File "/home/zhijin.wang/work/PyramidBox/layers/functions/detection.py", line 46, in forward
    decoded_boxes = decode(loc_data[i], prior_data, self.variance)
  File "/home/zhijin.wang/work/PyramidBox/layers/box_utils.py", line 231, in decode
    priors[:, :2] + loc[:, :2] * variances[0] * priors[:, 2:],
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #2 'other'

**Comment by Yuxiang1995** [comment]
@ForestWang  I meet the same error with you,have you fixed it? thanks

**Comment by nuanyang123** [comment]
@ForestWang  I met the same error with you,have you fixed it? thanks

**Comment by abcdvzz** [comment]
@Edwardmark 
Could u pls release your code for Pytorch 0.4?

**Comment by Yuxiang1995** [comment]
@ForestWang modify the code at line 302 in PyramidBox/pyramid.py 
self.priors.type(type(x.data))
convert to
self.priors.type(torch.Tensor.type(x.detach()))

And it works.

**Comment by Re3write** [comment]
@kernel-Peanut hello,i fix the type problem but i got  this error

 ids, count = nms(boxes, scores, self.nms_thresh, min(boxes.shape[0],self.nms_top_k))
ValueError: not enough values to unpack (expected 2, got 0)

do u know how to fix it?

**Comment by zerofo** [comment]
the same error 
ids, count = nms(boxes, scores, self.nms_thresh, min(boxes.shape[0],self.nms_top_k))
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Yuxiang1995** [comment]
@Re3write @zerofo 
I fix all the errors two months ago,but I am sorry that I forget now...
I suggest you read the source code carefully, and you can fix the error

**Comment by zerofo** [comment]
give up . use mtcnn back

**Comment by xjock** [comment]
> @kernel-Peanut hello,i fix the type problem but i got this error
> 
> ids, count = nms(boxes, scores, self.nms_thresh, min(boxes.shape[0],self.nms_top_k))
> ValueError: not enough values to unpack (expected 2, got 0)
> 
> do u know how to fix it?

Just check if len(boxes) is 0, then continue.

**Comment by Edwardmark** [comment]
@abcdvzz follow the link: https://github.com/amdegroot/ssd.pytorch/issues?utf8=%E2%9C%93&q=0.4
