### ISSUE TITLE
Error in layers/functions/box_utils

### ISSUE THREAD

**Issue by rlrahulkanojia** [Goingqs/PyramidBox#57]
/home/gaurav/Documents/rahul/WIDER_FACE/WIDER_val/images/0--Parade/0_Parade_marchingband_1_465.jpg
shrink:1
test.py:48: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x = Variable(x.cuda(), volatile=True)
/home/gaurav/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:2404: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/gaurav/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/gaurav/Documents/rahul/PyramidBox/pyramid.py:254: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(torch.cat([p for p in prior_boxs],0),volatile=True)
/home/gaurav/Documents/rahul/PyramidBox/pyramid.py:255: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors_head = Variable(torch.cat([p for p in prior_head_boxes],0),volatile=True)
/opt/conda/conda-bld/pytorch_1573049304260/work/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
Traceback (most recent call last):
  File "test.py", line 243, in <module>
    det0 = detect_face(image, shrink)  # origin test
  File "test.py", line 51, in detect_face
    y = net(x)
  File "/home/gaurav/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaurav/Documents/rahul/PyramidBox/pyramid.py", line 302, in forward
    self.priors.type(type(x.data))                  # default boxes
  File "/home/gaurav/Documents/rahul/PyramidBox/layers/functions/detection.py", line 46, in forward
    decoded_boxes = decode(loc_data[i], prior_data, self.variance)
  File "/home/gaurav/Documents/rahul/PyramidBox/layers/box_utils.py", line 231, in decode
    priors[:, :2] + loc[:, :2] * variances[0] * priors[:, 2:],
RuntimeError: expected device cuda:0 but got device cpu

**Comment by supremboy** [comment]
i met the same problem too,my env uses cuda10.1 and pytorch1.3.1.which version of pytorch do you use
